version: 2.1

jobs:
  build:
    docker: 
      - image: quay.io/biocontainers/deepstats:0.4--0
    steps:
      - checkout # check out the code in the project directory
      - run: find . -type f -name '*.R'
      - run: chmod +x tests/tests.R
      - run: ./tests/tests.R
