version: 2.1

jobs:
  build:
    docker: 
      - image: quay.io/widen/ubuntu:18.04-ubuntu1804-20200213
    steps:
      - checkout # check out the code in the project directory
      - run: chmod +x .circleci/setup_conda.sh
      - run: apt-get update
      - run: apt-get install -y zlib1g curl
      - run: ./.circleci/setup_conda.sh
      - run: chmod +x tests/tests.R
      - run: ./tests/tests.R
