version: 2.1

variables:
  linux: &linux
    machine: true

jobs:
  build:
    docker: 
      - image: quay.io/biocontainers/deepstats:0.3.1
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  # build and test on linux
  test-linux:
    <<: *linux
    steps:
      - checkout
      - run: .tests/tests.R
