# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

variables:
  setup: &setup
    run:
      name: Setup bioconda-utils
      command: .circleci/setup.sh
   exec: &exec
    run:
      name: Execute tests
      command: .tests/tests.R     
  

jobs:
  test:
    steps:
    - setup
    - exec
