version: 2.1

variables:
  linux: &linux
    machine: true

jobs:
  build:
    docker: 
      - image: quay.io/biocontainers/deepstats:0.4--0
    steps:
      - checkout # check out the code in the project directory
      - run : sudo apt-get update
      - run : sudo apt-get upgrade
      - run : sudo apt-get install git
      - run: git clone https://github.com/gtrichard/deepStats
      - run: cd deepStats
      - run: chmod +x tests/tests.R
      - run: .tests/tests.R
