version: 2.1

jobs:
  build:
    docker: 
      - image: quay.io/biocontainers/deepstats:0.4--0
    steps:
      - checkout # check out the code in the project directory
      - run: chmod +x .circleci/setup_conda.sh
      - run: ./.circleci/setup_conda.sh
      - run: chmod +x tests/tests.R
      - run: ./tests/tests.R
